"use client"
import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./components/AuthProvider";
import { NextUIProvider } from "@nextui-org/react";
import { Toaster } from 'sonner';
import ModalLayout from "./components/ModalLayout";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Ordering System",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <NextUIProvider>
            <AuthProvider>
              {children}
              <Toaster richColors  />
            </AuthProvider>
          </NextUIProvider>
        </main>
      </body>
    </html>
  );
}
